#!/bin/usr/python
#-*- coding: utf8 -*-
import os, getpass, re, time

os.system("clear")

                                                             
#................................................................................Data: 04/03/2018                        
#................................................................................Wilson                               
#................................................................................Obrigado Teacher pela oportunidade  
                                                               


def nome():
    Nome = raw_input("Digite o seu nome: ")
    match = re.match ('[0-9.-\=_,><?:;!@#$%"&*()_+"\]', Nome)
    if match:
        print 'Oloko... Está Válido!'
        time.sleep(1)
        os.system("clear")
    else:
        print 'Inválido... Passa amanhã...!'
        time.sleep(2)
        os.system("clear")
        print 'Tenta mais uma vez: '
        nome()
nome()

def email():
    Email = raw_input("Digite o seu  e-mail: ")
    match = re.match ('^[a-z]+([._-]?[0-9a-z]+|[0-9])*@[a-z]+([._-]?[0-9a-z]+|[0-9])*(\.com|\.br|.\com\.br)$' , Email)
    if match:
        print 'Oloko... Está Válido!'
        time.sleep(1)
        os.system("clear")
    else:
        print 'Inválido... Passa amanhã...!'
        time.sleep(2)
        os.system("clear")
        print 'Tenta mais uma vez: '
        email()
email()


def telefone():
        print 'Formato do número de telefone: (DDD) xxxx-xxxx'
        Telefone = raw_input("Informe o número do telefone: ")
        match = re.match ('^[(][0-9]{2}[)][ ][0-9]{4}[-][0-9]{4}$' , Telefone)
        if match:
             print 'Oloko... Está Válido!'
             time.sleep(1)
             os.system("clear")
        else:
             print 'Inválido... Passa amanhã...!'
             time.sleep(2)
             os.system("clear")
             print 'Tenta mais uma vez: '
             telefone()
telefone()

def rg():
        RG = raw_input("Informe o número do seu RG: ")
        match = re.match ('^[0-9]{2}\.[0-9]{3}\.[0-9]{3}[-][a-z0-9]$' , RG)
        if match:
            print 'Oloko... Está Válido!'
            time.sleep(1)
            os.system("clear")
        else:
            print 'Inválido... Passa amanhã...!'
            time.sleep(2)
            os.system("clear")
            print 'Tenta mais uma vez: '
            rg()
rg()

def cpf():
        CPF = raw_input("Informe o número do seu CPF: ")
        match = re.match ('^[0-9]{3}\.[0-9]{3}\.[0-9]{3}[-][0-9]{2}$' , CPF)
        if match:
            print 'Oloko... Está Válido!'
            time.sleep(1)
            os.system("clear")
        else:
            print 'Inválido... Passa amanhã...!'
            time.sleep(1)
            os.system("clear")
            print 'Tenta mais uma vez: '
            cpf()
cpf()

def data():
        print 'Formato da data: dd/mm/aaaa'
        DATA = raw_input("Informe a sua data de nascimento: ")
        match = re.match ('^(0[1-9]|[12][0-9]|3[0-1])/?(0[1-9]|1[0-2])/?(200[0-9]|201[0-8]|19[0-9]{2})$' , DATA)
        if match:
            print  'Oloko... Data Válida!'
            time.sleep(1)
            os.system("clear")
        else:
            print 'Inválido... Passa amanhã...!'
            time.sleep(2)
            os.system("clear")
            print 'Tenta mais uma vez: '
            data()
data()

def ip():
        IP = raw_input("Informe o seu IP: ")
        match = re.match ('^([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])){3}$', IP)
        if match:
            print 'Oloko... Está Válido!'
            time.sleep(1)
            os.system("clear")
        else:
            print 'Inválido... Passa amanhã...!'
            time.sleep(2)
            os.system("clear")
            print 'Tenta mais uma vez: '
            ip()
ip()

def mask():
        Mascara = raw_input("Informe sua Mascara: ")
        match = re.search(r'^(254|252|248|240|224|192|128)(.0){3}$|^255(.255|.254|.252|.248|.240|.224|.192|.128|.0){3}$', Mascara)
        if match:
            print 'Oloko... Está Válido!'
            time.sleep(1)
            os.system("clear")
        else:
            print 'Inválido... Passa amanhã...!'
            time.sleep(2)
            os.system("clear")
            print 'Tenta mais uma vez: '
            mask()
mask()
